--
-- DATA Only
-- 
-- Members
--
INSERT INTO `PASSE_COQUE_MEMBERS` (`EMAIL`, `LAST_NAME`, `FIRST_NAME`, `TARIF`, `AMOUNT`, `TELEPHONE`, `FIRST_ENROLLED`, `NEWS_LETTER_OK`, `PASSWORD`, `ADMIN_PRIVILEGES`, `SOME_CONTENT`) VALUES
('2l2telecnav@gmail.com', 'Lavallet', 'Laurent', 'r%C3%A9f%C3%A9rent+%2F+Mirage+28', NULL, NULL, NULL, 1, NULL, 0, NULL),
('421jimmypahun@gmail.com', 'Pahun', 'Jimmy', 'Donateur/membre d\'office', 5000, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('accueil.kernevest.bzh@outlook.fr', 'GUIGO', 'Marie Celine', 'ecole de voile', NULL, NULL, NULL, 1, NULL, 0, NULL),
('adele.delahaye@orange.fr', 'Delahaye', 'Adele', 'Felicie', 200, NULL, NULL, 1, NULL, 0, NULL),
('admin@passe-coque.com', 'Administrator', '%28careful+with+that%29', 'N%2FA', NULL, NULL, NULL, 0, '1a8565a9dc72048ba03b4156be3e569f22771f23', 1, 'Created to mess with the DB and other touchy stuff.'),
('adrien.chatel@hotmail.com', 'Chatel', 'Adrien', 'Membres FELICIE', 200, '324 92 49 55 88', '2022-02-01 23:00:00', 1, NULL, 0, NULL),
('alain.hahusseau@sfr.fr', 'Hahusseau', 'Alain', 'Skipper+r%C3%A9f%C3%A9rent', 200, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('alain.pichavant1@gmail.com', 'Pichavant', 'alain', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('aldoror@gmail.com', 'LAGUERRE', 'Bernard', 'Passeur d\'Ecoute', 50, '06 22 09 56 26', '2021-09-08 22:00:00', 1, NULL, 0, NULL),
('alice.flot@outlook.com', 'Flot', 'alice', 'don unique', 60, NULL, NULL, 0, NULL, 0, NULL),
('alixthomas.riviere@gmail.com', 'Riviere', 'Alix et Thomas', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('ambroiseaubert@yahoo.fr', 'Aubert', 'Ambroise', 'adhérent', NULL, NULL, NULL, 1, NULL, 0, NULL),
('an.mandet@hotmail.fr', 'Mandet', 'antoine', 'Felicie', NULL, NULL, NULL, 1, NULL, 0, NULL),
('andres.juan@wanadoo.fr', 'Andres', 'Jean+Marie', 'skipper+r%C3%A9f%C3%A9rent+super+maica+Mirella', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Anne-Sophie.MEYSSELLE@bpgo.fr', 'Meysselle', 'Anne-Sophie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('anne.auroux@passeurdecoute.fr', 'Auroux', 'Anne', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('annedebagneaux-savatier@uncl.com', 'De Bagneaux-Savatier', 'Anne', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('antenor@wanadoo.fr', 'Roig', 'Alain', 'Donateur/membre d\'office', 6000, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('antoine.beauquin@outlook.fr', 'beauquin', 'antoine', 'Membres FELICIE', 200, '06 88 33 21 94', '2021-08-29 22:00:00', 1, NULL, 0, NULL),
('antoinemei@hotmail.com', 'Messonier', 'Antoine', 'don unique', 20, NULL, NULL, 1, NULL, 0, NULL),
('antoine_pierreo@hotmail.com', 'Antoine', 'Pierre Olivier', 'don unique', 150, NULL, NULL, 1, NULL, 0, NULL),
('Arbri1994daiu@gmail.com', 'Dalu', 'Abri', 'Felicie', 200, NULL, NULL, 1, NULL, 0, NULL),
('arsacjeanne@gmail.com', 'Arsac', 'Jeanne', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('arsene@loceandespossibles.com', 'Rousseau', 'Ars%C3%A8ne', 'Patriarch', NULL, NULL, NULL, 1, NULL, 0, 'Goelette Patriarch'),
('arthur.levaillant@gmail.com', 'Levaillant', 'arthur', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('assotraverse@gmail.com', 'Marquestaut', 'Sophie', 'Asso traverse', NULL, NULL, NULL, 1, NULL, 0, NULL),
('atelier.antoinecampos@gmail.com', 'Campos', 'antoine', 'don unique', 80, NULL, NULL, 1, NULL, 0, NULL),
('augustin.fdherouel@gmail.com', 'Fouquet d\'herouel', 'augustin', 'membre felicie', 200, NULL, NULL, 1, NULL, 0, NULL),
('Aurelie.chaballier@gmail.com', 'Chaballier', 'Aurelie', 'Skipper référent', 200, '06 95 98 92 92', '2021-05-12 22:00:00', 1, NULL, 0, NULL),
('axellefauv11@gmail.com', 'Fauvel', 'Axelle', 'Skipper+r%C3%A9f%C3%A9rent', 200, '06 62 43 03 97', '2021-09-16 22:00:00', 0, NULL, 0, NULL),
('azevedo_francis@hotmail.com', 'AZEVEDO', 'Francis', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('basile.gueulle@gmail.com', 'Gueulle', 'Basile', 'Membres FELICIE', 200, '07 66 74 06 84', '2021-08-10 22:00:00', 1, NULL, 0, NULL),
('bcfre@orange.fr', 'Poissonnier', 'Fred', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('benedicte.lunven@sailowtech.ch', 'Lunven', 'Benedicte', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('Benhoch123@gmail.com', 'Hochart', 'Benoit', 'Skipper+r%C3%A9f%C3%A9rent', 200, '06 60 83 25 17', '2021-08-28 22:00:00', 1, NULL, 0, NULL),
('benjamin.rasseneur@laposte.net', 'Rasseneur', 'Benjamin', 'Refernet Kelt', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Benji.catry@gmail.com', 'Catry', 'Benjamin', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('benoit.leplatre@icloud.com', 'Leplatre', 'Benoit', 'Donateur/membre d\'office', NULL, NULL, NULL, 1, NULL, 0, NULL),
('berenice.schell@gmail.com', 'Schell', 'Berenice', 'Schift Project', NULL, NULL, NULL, 1, NULL, 0, NULL),
('bernardmiens@bbox.fr', 'Miens', 'Bernard', 'Membre OGS', 80, '07 62 80 69 66', '2021-10-14 22:00:00', 1, NULL, 0, NULL),
('besserve.noemie@gmail.com', 'Berserve', 'Noemie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('billiemarine@wanadoo.fr', 'Billie', 'Marine', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('blevin.pierre@orange.fr', 'Blevin', 'Pierre', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('bmenuet@wanadoo.fr', 'Menuet', 'Bernard', 'r%C3%A9f%C3%A9rent+%2F+Neptune', NULL, NULL, NULL, 1, NULL, 0, NULL),
('bouan.g@gmail.com', 'Bouan', 'Guillaume', 'Skipper référent', 200, '06 34 33 44 71', '2021-04-29 22:00:00', 1, NULL, 0, NULL),
('brieuc.morin@sellor.com', 'Morin', 'Brieuc', 'Sellor', NULL, NULL, NULL, 1, NULL, 0, NULL),
('brieucchaboisson98@gmail.com', 'Chaboisson', 'Brieuc', 'Membres FELICIE', 200, '06 58 79 75 95', '2021-09-08 22:00:00', 1, NULL, 0, NULL),
('brigitte.lanet@orange.fr', 'LANET', 'Brigitte', 'Passeur d\'Ecoute', 50, '06 25 01 79 16', '2021-08-17 22:00:00', 1, NULL, 0, NULL),
('brignon.bernard@orange.fr', 'Brignon', 'Bernard', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('bruno.trouble2@gmail.com', 'troubl%C3%A9', 'Bruno', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('bruno@recoules-assurances.com', 'RECOULES', 'Bruno', 'Passeur d\'Ecoute', 50, '06 80 07 66 86', '2021-08-17 22:00:00', 1, NULL, 0, NULL),
('bvoisard@nauti-link.fr', 'Voisard', 'Bruno', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('c.faivre@aixluberon.auction', 'Faivre', 'C', NULL, NULL, NULL, NULL, 0, NULL, 0, NULL),
('c.gautier@compagniedesportsdumorbihan.fr', 'Gautier', 'C', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('CalixteBERGER@hotmail.com', 'Berger', 'Calixte', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('camilledelabaere@gmail.com', 'Delabaere', 'Camille', 'Skipper référent', 200, '06 51 49 71 57', '2021-08-15 22:00:00', 1, NULL, 0, NULL),
('canardboat@yahoo.fr', 'Bonnefoy', 'Marie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('cantauthierry@hotmail.com', 'Cantau', 'thierry', 'Felicie', NULL, NULL, NULL, 1, NULL, 0, NULL),
('carl.streissel@gmail.com', 'Streissel', 'Carl', 'Skipper référent', 200, '06 14 29 16 11', '2021-05-17 22:00:00', 1, NULL, 0, NULL),
('caroleredt@lilo.org', 'Redt', 'Carole', 'Equipier', 5, '06 90 50 08 63', '2021-04-04 22:00:00', 1, NULL, 0, NULL),
('catherine.chabaud@europarl.europa.eu', 'Chabaud', 'Catherine', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('catherine.laguerre@hotmail.com', 'Laguerre', 'Catherine', NULL, NULL, NULL, NULL, 1, 'b572f2c7a208ad3ff5d6aff535421a5a8d32e4b5', 1, 'From the board !'),
('ccolimard@gmail.com', 'Colimard', 'Cl%C3%A9mence', 'Membres+FELICIE', 200, '06 86 48 00 62', '2021-06-23 22:00:00', 1, NULL, 0, NULL),
('cdormoy@free.fr', 'Dormoy', 'Carole', 'don unique', 20, NULL, NULL, 1, NULL, 0, NULL),
('celine.beaudon@gmail.com', 'Beaudon', 'C%C3%A9line', 'Membres+FELICIE', 200, '06 32 14 74 22', '2022-02-01 23:00:00', 1, NULL, 0, NULL),
('celine.kahn@oceanascommon.org', 'Kahn', 'C%C3%A9line', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('cfmoulin@orange.fr', 'Moulin', 'Francois', NULL, 200, NULL, NULL, 1, NULL, 0, NULL),
('ch.devaux@icloud.com', 'Devaux', 'Christian', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('ch.pelhate@gmail.com', 'Pelhate', 'Chantal', 'Equipier', 5, '06 83 34 72 10', '2022-01-03 23:00:00', 1, NULL, 0, NULL),
('cha.laurent.2@gmail.com', 'Laurent', 'Chantal', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('chausey1@free.fr', 'Bernard', 'Remy', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('chbourdy@hotmail.com', 'Bourdy', 'Christophe', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('chenoir.raphael@live.fr', 'Chenoir', 'Rapha%C3%ABl', 'Membres+FELICIE', 200, '06 08 50 76 87', '2022-01-13 23:00:00', 1, NULL, 0, NULL),
('chevreriedelapoterie@gmail.com', 'Boiteux', 'Catherine', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('christbint@hotmail.com', 'Binie', 'christian', 'don unique', 60, NULL, NULL, 1, NULL, 0, NULL),
('Christelle.bordetbonnefoy@gmail.com', 'Bordet', 'Christelle', 'adhesion', 50, NULL, NULL, 1, NULL, 0, NULL),
('christine.briand@wanadoo.fr', 'Briand', 'Christine', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('Christophe.BACON@saipem.com', 'Bacon', 'Christophe', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('christophequesnel06@gmail.com', 'Quesnel', 'Christophe', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('christophesoares@navicom.fr', 'Soares', 'Christophe', 'Navicom', NULL, NULL, NULL, 1, NULL, 0, NULL),
('christophe_roth@orange.fr', 'Roth', 'Christophe', 'Membres FELICIE', 200, '06 30 61 97 48', '2021-07-18 22:00:00', 1, NULL, 0, NULL),
('claire.hannecart@protonmail.com', 'hannecart', 'Claire', 'equipiere 5 e', 5, NULL, NULL, 1, NULL, 0, NULL),
('claire.lesurmagois@icloud.com', 'Lesur Magois', 'claire', 'Passeur d\'Ecoute', 50, '06 37 62 87 70', '2022-01-07 23:00:00', 1, NULL, 0, NULL),
('clairedelacotte@live.fr', 'Delacotte', 'Claire', 'don unique', 60, NULL, NULL, 1, NULL, 0, NULL),
('claradegasquet@gmail.com', 'de Gasquet', 'Clara', 'Membres FELICIE', 200, '06 99 31 80 78', '2021-07-18 22:00:00', 1, NULL, 0, NULL),
('clin.pauline@gmail.com', 'Clin', 'Pauline', 'don unique', 50, NULL, NULL, 1, NULL, 0, NULL),
('clotilde.beauperin1@gmail.com', 'beauperin', 'Clotilde', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('cmcelibert@hotmail.com', 'CELIBERT+', 'Claude+', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('coherence.ing@gmail.com', 'CAUCHY', 'Laurent', 'Skipper référent', 200, '06 60 93 99 80', '2021-10-23 22:00:00', 1, NULL, 0, NULL),
('Colin.chaballier@gmail.com', 'Chaballier', 'Colin', 'Skipper référent', 200, '06 21 11 65 03', '2021-05-12 22:00:00', 1, NULL, 0, NULL),
('colinebarraud@hotmail.fr', 'Barraud', 'Coline', 'Skipper référent', 200, '06 27 91 32 78', '2021-06-16 22:00:00', 1, NULL, 0, NULL),
('colinechabran@sfr.fr', 'chabran', 'coline', 'Skipper référent', 200, NULL, '2021-05-09 22:00:00', 0, NULL, 0, NULL),
('contact.watter@gmail.com', 'Watter', 'equipage', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('contact@latonnelleavins.fr', 'Melia', 'Guy', NULL, NULL, NULL, NULL, 1, '77ae2fdd1b890e82df27862c0a894615caf5a42e', 1, 'Boat-Club manager !'),
('contact@passe-coque.com', 'PASSE+COQUE', 'Contact', 'Personne+Morale', NULL, NULL, NULL, 0, NULL, 0, 'Admin. Used as referent for some boats.'),
('contact@voyageenpatrimoine.fr', 'Gasse', 'Wenceslas', 'Asso partenaire', 300, '06 52 25 75 26', '2021-03-24 23:00:00', 1, NULL, 0, NULL),
('cyril.blancart@hotmail.fr', 'Blancart', 'Cyril', 'Skipper référent', 200, '06 65 15 74 03', '2021-04-23 22:00:00', 1, NULL, 0, NULL),
('cyrille.isaac@gmail.com', 'Isaac Sibille', 'Cyrille', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('d.b.services.bb@gmail.com', 'Boutry', 'Benoit', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('d.fauvet@sailing-atlantic.com', 'Fauvet', 'Denis', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('david.contact2106@gmail.com', 'Guigue', 'david', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('deguibert.bene@gmail.com', 'De Guibert', 'antoine', 'don unique', NULL, NULL, NULL, 1, NULL, 0, NULL),
('denis.cuirinier@gmail.com', 'Cuirinier', 'Denis', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('didier.greggory@gmail.com', 'Gregory', 'Didier', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('Didier.LEDIODIC@bpgo.fr', 'Le Diodic', 'Didier', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('didier.pineau@vulcani.fr', 'Pineau', 'Didier', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('dimitri@yellow-impactsailing.com', 'Caudrelier', 'Dimitri', 'Yellow', NULL, NULL, NULL, 1, NULL, 0, NULL),
('dmgbnrn@gmail.com', 'Deguillebon de resnes', 'Dominique marie', 'don unique', 50, NULL, NULL, 1, NULL, 0, NULL),
('Dominique.deponsay@fondation-patrimoine.org', 'Deponsay', 'Dominique', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('dominique.petermuller@orange.fr', 'Petermuller', 'Dominique', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('dominiquejannin9@gmail.com', 'Jannin', 'Dominique', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('ehrenmannm@gmail.com', 'Ehrenmann', 'Maxime', 'Membres FELICIE', 200, '06 67 44 31 80', '2021-06-19 22:00:00', 1, NULL, 0, NULL),
('elisa.guizouarn@gmail.com', 'Guizouarn', 'Elisa', 'Skipper référent', 200, '06 38 80 17 91', '2021-05-27 22:00:00', 1, NULL, 0, NULL),
('emma34380@hotmail.fr', 'Calvet', 'Emma', 'Equipier', 5, '06 46 28 41 59', '2021-10-28 22:00:00', 1, NULL, 0, NULL),
('eric.de.wolbock@me.com', 'Dewolbock', 'Eric', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('etesek.pillet@yahoo.fr', 'Pillet', 'emelyne', 'Donateur/membre d\'office', 185, NULL, NULL, 1, NULL, 0, NULL),
('expert.maritime.garnier@gmail.com', 'Garnier', 'Jerome', 'expert ddt', NULL, NULL, NULL, 1, NULL, 0, NULL),
('f.ledevic@free.fr', 'Le devic', 'Franck', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('fabienstsupery@gmail.com', 'Saint-Sup%C3%A9ry', 'Fabien', 'Membres+FELICIE', 200, '06 77 18 50 05', '2021-06-22 22:00:00', 1, NULL, 0, NULL),
('fchaussier@gmail.com', 'Chaussier', 'Fanny', 'Membres FELICIE', 200, '06 72 66 68 54', '2022-01-05 23:00:00', 1, NULL, 0, NULL),
('fd@technique-voile.com', 'Duthil', 'frederic', 'technique voiles', NULL, NULL, NULL, 1, NULL, 0, NULL),
('florencecocaud@gmail.com', 'COCAUD MIENS', 'Florence', 'Passeur d\'Ecoute', 50, '07 62 80 69 66', '2021-10-13 22:00:00', 1, NULL, 0, NULL),
('florent.pelhate@gmail.com', 'Pelhate', 'Florent', 'Passeur d\'Ecoute', 50, '06 86 64 68 56', '2022-01-03 23:00:00', 1, NULL, 0, NULL),
('florian.pastier@orange.fr', 'Pastier', 'Florent', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('floriane.tchikladze@gmail.com', 'Tchikladze', 'Floriane', 'referente trehudal', NULL, NULL, NULL, 1, NULL, 0, NULL),
('follenfant.hubert@neuf.fr', 'Follenfant', 'Hubvert', 'coureur VIP', NULL, NULL, NULL, 1, NULL, 0, NULL),
('foucher-poignat@orange.fr', 'Foucher-Poignat', '', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('francesco.gandolfi@gmx.com', 'Gandolfi', 'Francesco', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('francis.brucelle@wanadoo.fr', 'Bucelle', 'Francis', 'menbre donateurs', 200, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('Franck.BERSON@bpgo.fr', 'Berson', 'Franck', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('francois.de.champs@hotmail.fr', 'de+Champs', 'Fran%C3%A7ois', 'Skipper+r%C3%A9f%C3%A9rent', 200, '06 82 46 42 12', '2021-08-11 22:00:00', 1, NULL, 0, NULL),
('fred.epmg@gmail.com', 'Gougeon', 'Fr%C3%A9d%C3%A9ric', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('fred.shifter@proton.me', 'Sfiter', 'Fred', 'Schift Project', NULL, NULL, NULL, 0, NULL, 0, NULL),
('fx.decrecy@voilemagazine.com', 'de+Crecy', 'Fran%C3%A7ois+Xavier', 'Personne+Morale', NULL, NULL, NULL, 1, NULL, 0, 'Referent de Saudade. Voile Magazine.'),
('g.jaffry@chasse-maree.fr', 'JAFFRY', 'Gwendal', 'Chasse marée', NULL, NULL, NULL, 1, NULL, 0, NULL),
('gallibaptiste8@gmail.com', 'galli', 'baptiste', 'Skipper+r%C3%A9f%C3%A9rent', 200, NULL, '2021-04-29 22:00:00', 1, NULL, 0, NULL),
('garciaalain299@gmail.com', 'Garcia', 'Alain', 'Donateur/membre d\'office', NULL, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('germain.regis@orange.fr', 'Germain', 'Regis', 'Réfrérent /donateurs', 600, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('geronimo-8@live.fr', 'Benac', 'Sandrine', 'Felicie', NULL, NULL, NULL, 1, NULL, 0, NULL),
('gestion@snt-voile.org', 'Soci%C3%A9t%C3%A9+Nautique+de+la+Trinit%C3%A9-sur-mer', '', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('gillesbaladi@gmail.com', 'Baladi+', 'Gilles+', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('gonzague.delval@sfr.fr', 'Delval', 'Gonzague', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('grandcitronvert@gmail.com', 'Pasquier', 'Etienne', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('gsirgc@gsir.fr', 'Castel', 'Gilles', 'don unique', 100, NULL, NULL, 1, NULL, 0, NULL),
('gtrentesaux@gt-invest.com', 'Trentesaux', 'Gery', 'Donateur/membre d\'office', 5000, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('guenole.havard@decathlon.com', 'Harvard', 'Gwenol%C3%A9', 'Tribord', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Guillaume.blanc@posteo.net', 'Blanc', 'Guillaume', 'Equipier', 5, '06 29 59 59 18', '2021-10-28 22:00:00', 1, NULL, 0, NULL),
('guillaume.donval@gmail.com', 'Donval', 'Marie morgane', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('guillaume@noviomo.fr', 'Deligniere', 'guillaume', 'expert ddt', NULL, NULL, NULL, 1, NULL, 0, NULL),
('hamalyas@aol.com', 'Lambrecht', 'Lise', 'don unique', 35, NULL, NULL, 1, NULL, 0, NULL),
('Hammonpellen.avocat@gmail.com', 'Hammon+Pellen', 'Marie-Pierre', 'Avocate', NULL, NULL, NULL, 0, NULL, 0, NULL),
('hamonf08@gmail.com', 'Hamon', 'Fabiola', 'adjerentes', 50, NULL, NULL, 1, NULL, 0, NULL),
('haquin2@orange.fr', 'Haquin+Pahun', 'Myriam', 'adh%C3%A9sioinbs+X+2', 100, NULL, NULL, 1, NULL, 0, NULL),
('hdemenge@gmail.com', 'DEMENGE', 'Hubert', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('helemaurice@yahoo.fr', 'Maurice', 'H%C3%A9l%C3%A8ne', 'Equipier', 5, '07 69 28 97 34', '2022-01-03 23:00:00', 1, NULL, 0, NULL),
('hippolytedreyfus@orange.fr', 'Dreyfus', 'Hippolyte', 'Membres FELICIE', 200, '06 52 58 38 62', '2022-01-07 23:00:00', 1, NULL, 0, NULL),
('hortense.lp@gmail.com', 'Doumic', 'Hortense', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('hubertdelariviere@gmail.com', 'De la Reiviere', 'Hubert', 'Schift Project', NULL, NULL, NULL, 1, NULL, 0, NULL),
('ia.guyot-sionnest@outlook.com', 'Guyot-sonnest', 'arnaud', 'Don unique', 100, NULL, NULL, 1, NULL, 0, NULL),
('isseo.asso@gmail.com', 'Benard', 'Manon', 'r%C3%A9f%C3%A9rent+f%C3%A9licie', NULL, NULL, NULL, 1, NULL, 0, NULL),
('itzeldiaz@yahoo.com', 'Diaz', 'Itzel', 'Equipier', 5, '07 89 78 89 43', '2022-01-19 23:00:00', 1, NULL, 0, NULL),
('j-f.chesne@wanadoo.fr', 'Chesn%C3%A9', 'Jean-Fran%C3%A7ois', 'Passeur+d%27Ecoute', 50, '06 72 46 09 09', '2021-10-31 23:00:00', 1, NULL, 0, NULL),
('jacques.landron@orange.fr', 'Landron', 'Jacques', 'Particpe Futur', NULL, NULL, NULL, 1, NULL, 0, NULL),
('jc@seaviewprogress.com', 'Crasnier', 'Jean Christophe', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jean-marie.martzolf@orange.fr', 'Martzloff', 'Jean Marie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('Jean-Pierre.Mortreux@asagao.fr', 'Mortreux', 'Jean Pierre', 'CEEMF', NULL, NULL, NULL, 1, NULL, 0, NULL),
('jeanbaptiste.lacan@yahoo.fr', 'Lacan', 'Jean Baptiste', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jeanberthias@yahoo.fr', 'Berthias', 'Jean', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jeanpierreadam3@gmail.com', 'Adam', 'jean Pierre', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jeanpierrelode55@gmail.com', 'Lode', 'jean Pierre', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jeff.allais@hotmail.fr', 'Allais', 'Jean+Fran%C3%A7ois', NULL, NULL, NULL, NULL, 1, '80e558ed5a05e269dfbeb596436dc6cd9cc7c8d1', 1, NULL),
('jeromedormois@yahoo.fr', 'Dormois', 'J%C3%A9rome', NULL, NULL, NULL, NULL, 0, NULL, 0, NULL),
('jmca@wanadoo.fr', 'Chauvet', 'JM', 'GPO', NULL, NULL, NULL, 1, NULL, 0, NULL),
('jmpatier@yahoo.fr', 'Patier', 'jean Marie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jochen.krauth@sailcoop.fr', 'Krauth', 'Jochen', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jose.levaillant@free.fr', 'Levaillant', 'Jose', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jp.salaun@laposte.net', 'Salaun', 'JP', 'Voiles mag', NULL, NULL, NULL, 1, NULL, 0, NULL),
('jpc578@gmail.com', 'CAVÉ', 'Jean-Pierre', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('jules.despreaux@amer-mediterranee.org', 'Depreaux', 'Jules', 'Contact', NULL, NULL, NULL, 1, NULL, 0, NULL),
('jules.pasquier02@gmail.com', 'Pasquier', 'jules', 'Skipper référent', 200, '06 89 54 80 50', '2021-08-20 22:00:00', 1, NULL, 0, NULL),
('julien.bonnefoy@gmail.com', 'Bonnefoy', 'Julien', 'Donateur/membre d\'office', 200, NULL, NULL, 1, NULL, 0, NULL),
('juliette.eme.cp@gmail.com', 'EME', 'Juliette', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('julie_bignon@orange.fr', 'Bignon', 'Julie', 'Passeur d\'Ecoute', 50, '06 47 61 65 23', '2022-01-01 23:00:00', 1, NULL, 0, NULL),
('jurisbob@orange.fr', 'LAGUERRE', 'Fran%C3%A7ois', 'Passeur+d%27%C3%A9coute', 50, NULL, NULL, 1, NULL, 0, NULL),
('karina_jeribi@yahoo.fr', 'Jeridi', 'Karina', 'adherente', 50, NULL, NULL, 1, NULL, 0, NULL),
('karine.audoin@hotmail.com', 'Audouin', 'Karine', NULL, NULL, NULL, NULL, 0, NULL, 0, NULL),
('ken.woehrle@gmail.com', 'Woehrle', 'Ken', 'Skipper référent', 200, '06 65 64 42 26', '2021-08-21 22:00:00', 1, NULL, 0, NULL),
('kimanne.cherlock.leformal@orange.fr', 'Le Formal', 'Kim Anne', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('krystelle.besson@gmail.com', 'Besson', 'Christelle', 'don unique', NULL, NULL, NULL, 1, NULL, 0, NULL),
('l.brochard.archi@gmail.com', 'Brochard', 'Laurent', 'Skipper référent', 200, '06 08 50 05 80', '2021-06-26 22:00:00', 1, NULL, 0, NULL),
('L.MADELINE@voilesetvoiliers.com', 'Madeline', 'Loic', 'Voiles & Voiliers', NULL, NULL, NULL, 1, NULL, 0, NULL),
('lara.gatineaubochard.jd@gmail.com', 'Gatineau', 'Lara', 'felicie', NULL, NULL, NULL, 1, NULL, 0, NULL),
('lassalle.alexandre@yahoo.fr', 'lassale', 'Alexandre', 'é equipiers', NULL, NULL, NULL, 1, NULL, 0, NULL),
('laurence.corroler@editions-lariviere.com', 'Coroller', 'Laurence', 'voiles mag', NULL, NULL, NULL, 1, NULL, 0, NULL),
('laurent.armenaud@laposte.net', 'Armeneau', 'Laurent', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('lavat.benoit@wanadoo.fr', 'Lavat', 'Benoit', 'Donateur/membre d\'office', 150, NULL, NULL, 1, NULL, 0, NULL),
('lea.baziere@gmail.com', 'Bazi%C3%A8re', 'L%C3%A9a', 'Membres+FELICIE', 200, '06 30 13 31 68', '2021-06-12 22:00:00', 1, NULL, 0, NULL),
('lebc2228@gmail.com', 'Jovignot', 'Nathjalene', 'Felicie', NULL, NULL, NULL, 0, NULL, 0, NULL),
('leguel@outlook.fr', 'Legelvouit', 'Jean Yves', 'adherent', NULL, NULL, NULL, 1, NULL, 0, NULL),
('leore.pujol@oceanascommon.org', 'Pujol', 'Leore', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('lepecheur.g@gmail.com', 'Le+Pecheur', 'Guy', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('litimat1@free.fr', 'Leray', 'Jean Christophe', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('lmcouetoux@orange.fr', 'Couetoux', 'louis marie', 'don unique', 100, NULL, NULL, 1, NULL, 0, NULL),
('loic.ff@teamwinds.com', 'Fournier-Foch', 'loic', 'Passeur d\'Ecoute', 50, '06 63 39 07 56', '2021-06-25 22:00:00', 1, NULL, 0, NULL),
('lorraine.jacquot@orange.fr', 'Jaccot', 'Lorraine', 'don unique', 60, NULL, NULL, 1, NULL, 0, NULL),
('louis.laigle@neuf.fr', 'Laigle', 'Louis', NULL, NULL, NULL, NULL, 1, 'c6ee1e77751525e6a854dc9d7cc8c0d1b27c3546', 0, NULL),
('louise.bigot21@gmail.com', 'Bigot', 'Louise', 'Membres FELICIE', 200, '07 82 87 50 61', '2022-01-02 23:00:00', 1, NULL, 0, NULL),
('lucas.weber@live.fr', 'Weber', 'Lucas', 'felicie', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Lucie.dogramadjian@gmail.com', 'Dogramadjian', 'Lucie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('m.bardou@stphilibert.fr', 'Bardou', 'Marine', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('m4vrick99@gmail.com', 'Scmidt', 'Gregory', 'don unique', NULL, NULL, NULL, 1, NULL, 0, NULL),
('ma.bonnefoy@charentelibre.fr', 'Bonnefoy', 'Marie+aim%C3%A9e', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('maisonpetit@orange.fr', 'petit', 'G%C3%A9rard', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('manon.ligonesche@gmail.com', 'Ligonesh', 'Manon', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('manuel.oceanus.sailor@gmail.com', 'Garcia', 'Manu', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('mapieducap@orange.fr', 'Donval', 'Marie Pierre', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('marani.michel@orange.fr', 'Marani', 'Michel', 'Tombsy ex Hann', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Marc Flye marcflye@aol.com', 'Flye', 'Marc', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('margotpeutin@gmail.com', 'Peutin', 'Margot', 'Coriolan', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Marie.labussiere@gmail.com', 'Labussiere', 'Marie', 'felicie', 200, NULL, NULL, 1, NULL, 0, NULL),
('marieodilebotti@gmail.com', 'Botti', 'Marie Odile', 'Referente /Kim Anne', 400, NULL, NULL, 1, NULL, 0, NULL),
('mariepierre.labat-camy@csdental.com', 'Labat', 'MP', 'Donateur/membre d\'office', NULL, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('marine.prevet@atelierkopal.fr', 'Prevet', 'marine', 'referente/ passe partout', NULL, NULL, NULL, 1, NULL, 0, NULL),
('marinebulles@outlook.fr', 'Gabbay', 'Marine', 'membre donateurs', 150, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('marionduroselle@hotmail.com', 'Duroselle', 'Marion', 'Felicie', 200, NULL, NULL, 1, NULL, 0, NULL),
('marmajour@gmail.com', 'De Ravignan', 'Bernard', 'membre donateurs', 299, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('marrettijacopo@gmail.com', 'Maretti', 'Jacopo', 'equipieru', 5, NULL, NULL, 1, NULL, 0, NULL),
('martinmassot@hotmail.com', 'Massot', 'Martin', 'Membres FELICIE', 200, '06 49 62 40 63', '2021-06-23 22:00:00', 1, NULL, 0, NULL),
('maxencearridiaux@gmail.com', 'Arridiaux', 'Maxence', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('mbolonantes@gmail.com', 'Bolo', 'Mico', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('michel.vermeulen1000@orange.fr', 'Vermeulen', 'Michel', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('michelhorellou@gmail.com', 'Horellou', 'Michel', 'Donateur/membre d\'office', 350, NULL, NULL, 1, NULL, 0, NULL),
('mickael.verrier@lilo.org', 'VERRIER', 'Micka%C3%ABl', 'Membres+FELICIE', 200, '06 01 37 31 07', '2021-08-10 22:00:00', 1, NULL, 0, NULL),
('mike@mikehorn.com', 'Horn', 'Mike', 'Horn VIP', NULL, NULL, NULL, 1, NULL, 0, NULL),
('minaud.frederic@gmail.com', 'Minaud', 'Fr%C3%A9d%C3%A9ric', 'Membres+FELICIE', 200, '06 37 69 99 59', '2022-01-07 23:00:00', 1, NULL, 0, NULL),
('mlemeni@yahoo.fr', 'Lemeni', 'Michel', 'adh%C3%A9rent', 50, NULL, NULL, 1, NULL, 0, NULL),
('mmdonval@gmail.com', 'Donval', 'Guillaume', 'membre donbateur', 200, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('mobydicks.sail@gmail.com', 'Gateau', 'Stephane', 'Référent /donateurs', 350, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('modkozhasso@gmail.com', 'Leiglon', 'Gerard', 'Modkhoz asso', NULL, NULL, NULL, 1, NULL, 0, NULL),
('morisseauguillaume@msn.com', 'Morisseau', 'Guillaume', 'Skipper+r%C3%A9f%C3%A9rent', 200, NULL, '2021-05-04 22:00:00', 1, NULL, 0, NULL),
('mukojiro123@yahoo.fr', 'NEGRIER', 'Damien', 'Skipper référent', 200, '06 95 15 51 79', '2021-08-11 22:00:00', 1, NULL, 0, NULL),
('nav.solidaire@gmail.com', 'Nav Solidaires', '', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('ndulauroy@orange.fr', 'Dulauroy', 'Nicholas', 'CEEMF', NULL, NULL, NULL, 1, NULL, 0, NULL),
('nicogliss46@hotmail.fr', 'Bidon', 'Nicolas', 'Skipper référent', 200, NULL, '2021-04-26 22:00:00', 1, NULL, 0, NULL),
('nicolas.movio@gmail.com', 'Movio', 'Nicolas', 'Equipier', 5, '06 78 77 25 55', '2021-10-28 22:00:00', 1, NULL, 0, NULL),
('nicolashuardlamer@gmail.com', 'Lamer', 'Nicholas', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('nimaillard@icloud.com', 'Nicolas', 'Maillard', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News letter subscriber'),
('ninonp64@gmail.com', 'Chatard', 'Ninon', 'equipiere 5 e', 5, NULL, NULL, 1, NULL, 0, NULL),
('nolwennporhiel@gmail.com', 'PORHIEL', 'NOLWENN', 'Passeur d\'Ecoute', 50, '07 84 92 59 06', '2021-05-07 22:00:00', 1, NULL, 0, NULL),
('nouchkavercors@gmail.com', 'Alles', 'Nouchka', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('olivier.lediouris@gmail.com', 'Le+Diouris', 'Olivier', NULL, NULL, NULL, NULL, 1, 'b572f2c7a208ad3ff5d6aff535421a5a8d32e4b5', 0, 'For tests, on s\'en fout.\r\nPasse-Coque member, Boat-Club member. No admin.'),
('olivier@lediouris.net', 'Le+Diouris', 'Olivier', 'N%2FA', NULL, '+33 6 40 10 69 55', NULL, 1, '76d39ff72b5006ef54a27e9eb6746900fdeb324d', 1, 'I am the boss.\r\nThat\'s it!'),
('olivieramiot@gmx.fr', 'Amiot', 'olivier', 'Equipier', 5, '06 62 48 95 67', '2022-01-01 23:00:00', 1, NULL, 0, NULL),
('oriotjeannick@orange.fr', 'Oriot', 'Jannick', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('pa.onfray@orange.fr', 'Onfray', 'Patrick', NULL, 20, NULL, NULL, 1, NULL, 0, NULL),
('pabema@protonmail.com', 'Prontinio', 'Pamela', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('paco-andreo@orange.fr', 'Andreo', 'Paco', 'Skipper référent', 200, '06 49 36 51 89', '2021-09-19 22:00:00', 1, NULL, 0, NULL),
('panetrat@gmail.com', 'Panetrat', 'Gabrielle', 'Donateur/membre d\'office', 1500, NULL, NULL, 1, NULL, 0, NULL),
('parramoun@gmail.com', 'Arramounet', 'Patrick', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('pat.ay@hotmail.fr', 'Ayoul+', 'Patrick+', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('patbenoiton@gmail.com', 'Benoiton', 'Patrick', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('patrice.vnd@cegetel.net', 'Bujedo', 'Patrice', 'Carter', 25, NULL, NULL, 1, NULL, 0, NULL),
('Patricia Favre ', 'Favre', 'Patricia', 'Horn', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Patrick.Ballu@cadexi.com', 'Ballu', 'Patrick', 'Donateur/membre d\'office', NULL, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('patrick.hnge@free.fr', 'Hinge', 'Patrick', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News-Letter only.'),
('patrick.lecoindre@gmail.com', 'Lecoindre', 'Patrick', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('patrick.legait@free.fr', 'Legait', 'Patrick', 'adhérent', NULL, NULL, NULL, 1, NULL, 0, NULL),
('patrick.potiron1@orange.fr', 'Potiron', 'Patrick', 'Donateur/membre d\'office', NULL, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('paul.gury@editions-lariviere.com', 'GURY', 'Paul', 'Voilkes Mag', NULL, NULL, NULL, 1, NULL, 0, NULL),
('paul.melot@gmail.com', 'Melot', 'Paul', 'Statieur', NULL, NULL, NULL, 1, NULL, 0, NULL),
('paul.reveillon@gmail.com', 'Reveillon', 'Paul', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('paul.rodionoff@gmail.com', 'Rodionoff', 'Paul', 'Membres FELICIE', 200, '06 63 91 51 83', '2022-01-05 23:00:00', 1, NULL, 0, NULL),
('paulineantoine1@gmail.com', 'Aqntoine', 'Pauline', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('payen.roland@neuf.fr', 'Payen', 'Roland', 'Skipper référent', 200, '06 42 81 29 30', '2021-04-27 22:00:00', 1, NULL, 0, NULL),
('peche.jean-paul@wanadoo.fr', 'Peche', 'Servanne', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('peremax72@gmail.com', 'Deguibert', 'Maxime', 'don unique', 100, NULL, NULL, 1, NULL, 0, NULL),
('pgarenne@grand-pavois.com', 'Garenne', 'Pierrick', 'GPO', NULL, NULL, NULL, 1, NULL, 0, NULL),
('philippe.benoiton@gmail.com', 'Benoiton', 'Philippe', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('philippe.coindreau@gmail.com', 'Coindreau', 'Phlippe', 'Donateur/membre d\'office', 3000, '06 62 08 63 05', '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('philippe.jacques.roux@orange.fr', 'Roux', 'Philippe Jacques', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('phip56@me.com', 'Plisson', 'Philip', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('pierre.azeau@wanadoo.fr', 'Azeau', 'Pierre', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('pierrebenard@hotmail.com', 'Benard', 'Pierre', 'adheret. Isseo', NULL, NULL, NULL, 1, NULL, 0, NULL),
('pj.jannin@passeurdecoute.fr', 'Jannin', 'Pierre-Jean', 'Pr%C3%A9sident', NULL, NULL, '2018-12-31 23:00:00', 1, '7a9b761abc9578d103475e681f8f7b93b4918d29', 1, 'Le chef !'),
('plaurent@boomer.fr', 'Laurent', 'Philippe', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('pmoelo@thalos.fr', 'Moelo', 'Patrick', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('pommier.zoe@orange.fr', 'Pommier', 'Zo%C3%A9', 'Felicie', 200, NULL, NULL, 1, NULL, 0, NULL),
('prdelfosse@gmail.com', 'Delfosse', '', 'Mordhoz', NULL, NULL, NULL, 1, NULL, 0, NULL),
('prevet.jean-michel@orange.fr', 'Prevet', 'Jean Michel', 'don unique', 100, NULL, NULL, 1, NULL, 0, NULL),
('rayondesoleilmh@gmail.com', 'Hammi', 'Meriem', 'Equipier', 5, '06 59 25 68 01', '2021-11-12 23:00:00', 1, NULL, 0, NULL),
('rebecca.baudrier.archi@gmail.com', 'Baudrier', 'R%C3%A9becca', 'Equipier', 5, '06 66 11 03 57', '2021-11-16 23:00:00', 1, NULL, 0, NULL),
('regis.berleur@ventdebout.be', 'Berleur', 'regis', 'vent debout Belgique', NULL, NULL, NULL, 1, NULL, 0, NULL),
('relation.apadvdl@outlook.fr', 'Dennonain', 'Louis', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('remiviolet7@gmail.com', 'Violet', 'Remy', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('rene.berson@wanadoo.fr', 'Berson', 'Ren%C3%A9', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('rezotonik@gmail.com', 'Rezotonik', '', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('Richard.abadie2@wanadoo.fr', 'Abadie', 'Richard', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('riviere.daniel@club.fr', 'Riviere', 'Daniel', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('romainblanc7@gmail.com', 'Blanc', 'Romain', 'Skipper référent', 200, '06 89 61 70 36', '2021-05-08 22:00:00', 1, NULL, 0, NULL),
('roxanebalan@gmail.com', 'Balan', 'Roxane', 'Equipier', 5, NULL, '2021-10-30 22:00:00', 1, NULL, 0, NULL),
('r_one_71@yahoo.fr', 'Saliou', 'Ertwann', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('sanchez.claire67@gmail.com', 'Sanchez', 'Claire', 'Membres FELICIE', 200, '06 83 64 97 02', '2021-09-13 22:00:00', 1, NULL, 0, NULL),
('segolene.49@hotmail.fr', 'Cozanet', 's%C3%A9golene', 'don+unique', 25, NULL, NULL, 1, NULL, 0, NULL),
('sergebenard7@gmail.com', 'benard', 'Serge', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('sigrid.verwaerde@gmail.com', 'Verwaerde', 'Sigrid', 'Passeur d\'Ecoute', 50, '06 05 22 02 89', '2021-11-24 23:00:00', 1, NULL, 0, NULL),
('smenuet.evoceane@gmail.com', 'Menuet', 'St%C3%A9phane', 'membre', 50, NULL, '2021-02-01 23:00:00', 1, NULL, 0, 'Autre emails : \r\nst.menuet@wanadoo.fr,\r\nsmenuet@evoceane.fr\r\nsmenuet.evoceane@gmail.com'),
('solene.tchikladze@yahoo.fr', 'Tchikladz%C3%A9', 'solene', 'Skipper+r%C3%A9f%C3%A9rent', 200, '06 52 12 19 10', '2021-05-03 22:00:00', 1, NULL, 0, NULL),
('sophie.amable@yacht-concept.fr', 'amable', 'sophie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('sophie.gambier01@gmail.com', 'Gambier', 'Sophie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('srb@fondationdelamer.org', 'Roux de Bezieu', 'Sabine', 'Fondation de la mer', NULL, NULL, NULL, 1, NULL, 0, NULL),
('stephane.dierick@sailcoop.fr', 'Dierick', 'St%C3%A9phane', 'sailcoop', NULL, NULL, NULL, 1, NULL, 0, NULL),
('stephanehupin@gmail.com', 'Hupin', 'St%C3%A9phane', 'Skipper+r%C3%A9f%C3%A9rent', 200, '06 75 03 46 30', '2021-07-04 22:00:00', 1, NULL, 0, NULL),
('sylvie.pons-hermieu@laposte.net', 'Pons-Hermieu', 'Sylvie', 'Equipier', 5, '06 83 33 19 09', '2021-10-29 22:00:00', 1, NULL, 0, NULL),
('sylviemoniquebarbe@gmail.com', 'Barb%C3%A9', 'Sylvie', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('tarriere.benoit@orange.fr', 'Tarri%C3%A8re', 'Beno%C3%AEt', 'Passeur+d%27Ecoute', 50, '06 48 00 69 38', '2021-10-31 23:00:00', 1, NULL, 0, NULL),
('tchevillon@robinmarine.fr', 'Chevillon', 'Thierry', 'Robin Marine', NULL, NULL, NULL, 1, NULL, 0, NULL),
('tdurand@nautipark.com', 'Durant', 'Thomas', 'Nautipark', NULL, NULL, NULL, 1, NULL, 0, NULL),
('Teddy.Dufour@webasto.com', 'Dufour', 'Teddy', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('Thibaud.soret@gmail.com', 'Soret', 'Thibaud', 'Equipier', 5, NULL, '2022-01-14 23:00:00', 1, NULL, 0, NULL),
('thierry.cherpitel56@gmail.com', 'Cherpitel', 'Thierry', 'contact', NULL, NULL, NULL, 1, NULL, 0, NULL),
('thyol.michelin@cegetel.net', 'Michelin', 'Thierry', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('tiagocampostc@hotmail.com', 'Campos', 'Tiago', 'referent evasion 32', NULL, NULL, NULL, 1, NULL, 0, NULL),
('torre.colin@gmail.com', 'Torre', 'Colin', 'don unque', 20, NULL, NULL, 1, NULL, 0, NULL),
('unjourdaout@gmail.com', 'De Puyraymond', 'Didier', 'Donateur/membre d\'office', 5000, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('vacher.jean@gmail.com', 'Vacher', 'Jean', 'adherent', 50, NULL, NULL, 1, NULL, 0, NULL),
('vallgerard@wanadoo.fr', 'Vall%C3%A9e', 'G%C3%A9rard', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('vernetchris@sfr.fr', 'Vernet', 'Christian', NULL, 50, NULL, NULL, 1, NULL, 0, NULL),
('vioparcot@gmail.com', 'PARCOT', 'Violaine', 'Equipier', 5, '06 74 78 62 30', '2021-10-28 22:00:00', 1, NULL, 0, NULL),
('voile193@yahoo.fr', 'Mallaret', 'Bernard', 'adheret VIP', NULL, NULL, NULL, 1, NULL, 0, NULL),
('vplcom@free.fr', 'Perrin Lacour', 'Vincent', 'Createur Logo', NULL, NULL, NULL, 0, NULL, 0, NULL),
('xavier.debec@gmail.com', 'De Becque', 'Xavier', 'Donateur/membre d\'office', 173, NULL, NULL, 1, NULL, 0, NULL),
('y.geny@nogoogle.fr', 'Geny', 'Yoann', NULL, NULL, NULL, NULL, 1, NULL, 0, 'News Letter Subscriber'),
('yachtsdupatrimoine@gmail.com', 'Huppin', 'Stephane', 'Skipper Référent', 200, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('yann.legrand56@icloud.com', 'Legrand', 'Yann', 'Skipper+R%C3%A9f%C3%A9rant', 200, NULL, '2021-02-01 23:00:00', 1, NULL, 0, NULL),
('yann.royer@sailcoop.fr', 'Royer', 'Yann', 'Sailcoop', NULL, NULL, NULL, 1, NULL, 0, NULL),
('yl6591@hotmail.fr', 'Brossard', 'Julie', 'equipiere 5 e', NULL, NULL, NULL, 1, NULL, 0, NULL),
('yves-aumont@club-internet.fr', 'Aumont', 'Yves', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('yves-aumont@laposte.net', 'AUMONT', 'Yves', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('yves.milza@gmail.com', 'Milza', 'Yves', NULL, NULL, NULL, NULL, 1, NULL, 0, NULL),
('yves1@netcourrier.com', 'Niort', 'Yves', 'Skipper référent', 200, '06 44 13 36 10', '2022-01-05 23:00:00', 1, NULL, 0, NULL);

--
-- Dumping data for table `MEMBER_FEES`
--

INSERT INTO `MEMBER_FEES` (`EMAIL`, `YEAR`) VALUES
('421jimmypahun@gmail.com', 2021),
('421jimmypahun@gmail.com', 2022),
('421jimmypahun@gmail.com', 2023),
('421jimmypahun@gmail.com', 2024),
('adele.delahaye@orange.fr', 2022),
('adrien.chatel@hotmail.com', 2022),
('alain.hahusseau@sfr.fr', 2021),
('alain.hahusseau@sfr.fr', 2022),
('aldoror@gmail.com', 2021),
('aldoror@gmail.com', 2022),
('alixthomas.riviere@gmail.com', 2022),
('ambroiseaubert@yahoo.fr', 2022),
('andres.juan@wanadoo.fr', 2023),
('andres.juan@wanadoo.fr', 2024),
('Anne-Sophie.MEYSSELLE@bpgo.fr', 2023),
('anne.auroux@passeurdecoute.fr', 2021),
('anne.auroux@passeurdecoute.fr', 2022),
('anne.auroux@passeurdecoute.fr', 2023),
('annedebagneaux-savatier@uncl.com', 2023),
('antenor@wanadoo.fr', 2021),
('antenor@wanadoo.fr', 2022),
('antoine.beauquin@outlook.fr', 2021),
('antoine.beauquin@outlook.fr', 2022),
('atelier.antoinecampos@gmail.com', 2022),
('Aurelie.chaballier@gmail.com', 2021),
('Aurelie.chaballier@gmail.com', 2022),
('axellefauv11@gmail.com', 2021),
('axellefauv11@gmail.com', 2022),
('azevedo_francis@hotmail.com', 2022),
('basile.gueulle@gmail.com', 2021),
('basile.gueulle@gmail.com', 2022),
('bcfre@orange.fr', 2023),
('Benhoch123@gmail.com', 2021),
('Benhoch123@gmail.com', 2022),
('Benji.catry@gmail.com', 2024),
('bernardmiens@bbox.fr', 2021),
('bernardmiens@bbox.fr', 2022),
('besserve.noemie@gmail.com', 2024),
('billiemarine@wanadoo.fr', 2023),
('bmenuet@wanadoo.fr', 2022),
('bmenuet@wanadoo.fr', 2023),
('bouan.g@gmail.com', 2021),
('bouan.g@gmail.com', 2022),
('bouan.g@gmail.com', 2023),
('brieucchaboisson98@gmail.com', 2021),
('brieucchaboisson98@gmail.com', 2022),
('brigitte.lanet@orange.fr', 2021),
('brigitte.lanet@orange.fr', 2022),
('bruno@recoules-assurances.com', 2021),
('bruno@recoules-assurances.com', 2022),
('c.gautier@compagniedesportsdumorbihan.fr', 2023),
('camilledelabaere@gmail.com', 2021),
('camilledelabaere@gmail.com', 2022),
('canardboat@yahoo.fr', 2024),
('carl.streissel@gmail.com', 2021),
('carl.streissel@gmail.com', 2022),
('carl.streissel@gmail.com', 2023),
('carl.streissel@gmail.com', 2024),
('caroleredt@lilo.org', 2021),
('caroleredt@lilo.org', 2022),
('ccolimard@gmail.com', 2021),
('ccolimard@gmail.com', 2022),
('celine.beaudon@gmail.com', 2022),
('celine.kahn@oceanascommon.org', 2023),
('ch.pelhate@gmail.com', 2022),
('chausey1@free.fr', 2023),
('chenoir.raphael@live.fr', 2021),
('chenoir.raphael@live.fr', 2022),
('chevreriedelapoterie@gmail.com', 2022),
('christbint@hotmail.com', 2022),
('Christelle.bordetbonnefoy@gmail.com', 2022),
('Christophe.BACON@saipem.com', 2023),
('christophequesnel06@gmail.com', 2023),
('christophesoares@navicom.fr', 2023),
('christophe_roth@orange.fr', 2021),
('christophe_roth@orange.fr', 2022),
('claire.lesurmagois@icloud.com', 2022),
('claradegasquet@gmail.com', 2021),
('claradegasquet@gmail.com', 2022),
('clin.pauline@gmail.com', 2021),
('coherence.ing@gmail.com', 2021),
('coherence.ing@gmail.com', 2022),
('Colin.chaballier@gmail.com', 2021),
('Colin.chaballier@gmail.com', 2022),
('Colin.chaballier@gmail.com', 2023),
('Colin.chaballier@gmail.com', 2024),
('colinebarraud@hotmail.fr', 2021),
('colinebarraud@hotmail.fr', 2022),
('colinechabran@sfr.fr', 2021),
('colinechabran@sfr.fr', 2022),
('contact@latonnelleavins.fr', 2023),
('contact@voyageenpatrimoine.fr', 2021),
('contact@voyageenpatrimoine.fr', 2022),
('cyril.blancart@hotmail.fr', 2021),
('cyril.blancart@hotmail.fr', 2022),
('cyrille.isaac@gmail.com', 2023),
('d.b.services.bb@gmail.com', 2023),
('denis.cuirinier@gmail.com', 2021),
('denis.cuirinier@gmail.com', 2022),
('Didier.LEDIODIC@bpgo.fr', 2023),
('didier.pineau@vulcani.fr', 2023),
('dimitri@yellow-impactsailing.com', 2023),
('dimitri@yellow-impactsailing.com', 2024),
('dmgbnrn@gmail.com', 2021),
('Dominique.deponsay@fondation-patrimoine.org', 2023),
('ehrenmannm@gmail.com', 2021),
('ehrenmannm@gmail.com', 2022),
('elisa.guizouarn@gmail.com', 2021),
('elisa.guizouarn@gmail.com', 2022),
('emma34380@hotmail.fr', 2021),
('emma34380@hotmail.fr', 2022),
('eric.de.wolbock@me.com', 2023),
('eric.de.wolbock@me.com', 2024),
('fabienstsupery@gmail.com', 2021),
('fabienstsupery@gmail.com', 2022),
('fchaussier@gmail.com', 2021),
('fchaussier@gmail.com', 2022),
('fd@technique-voile.com', 2023),
('florencecocaud@gmail.com', 2021),
('florencecocaud@gmail.com', 2022),
('florent.pelhate@gmail.com', 2022),
('floriane.tchikladze@gmail.com', 2023),
('foucher-poignat@orange.fr', 2023),
('francis.brucelle@wanadoo.fr', 2021),
('francis.brucelle@wanadoo.fr', 2022),
('Franck.BERSON@bpgo.fr', 2023),
('francois.de.champs@hotmail.fr', 2021),
('francois.de.champs@hotmail.fr', 2022),
('fred.epmg@gmail.com', 2021),
('fred.epmg@gmail.com', 2022),
('fred.epmg@gmail.com', 2023),
('gallibaptiste8@gmail.com', 2021),
('gallibaptiste8@gmail.com', 2022),
('garciaalain299@gmail.com', 2021),
('garciaalain299@gmail.com', 2022),
('germain.regis@orange.fr', 2021),
('germain.regis@orange.fr', 2022),
('gestion@snt-voile.org', 2023),
('grandcitronvert@gmail.com', 2023),
('gtrentesaux@gt-invest.com', 2021),
('gtrentesaux@gt-invest.com', 2022),
('gtrentesaux@gt-invest.com', 2023),
('Guillaume.blanc@posteo.net', 2021),
('Guillaume.blanc@posteo.net', 2022),
('hamonf08@gmail.com', 2023),
('helemaurice@yahoo.fr', 2022),
('hippolytedreyfus@orange.fr', 2022),
('hortense.lp@gmail.com', 2023),
('isseo.asso@gmail.com', 2022),
('isseo.asso@gmail.com', 2023),
('itzeldiaz@yahoo.com', 2022),
('j-f.chesne@wanadoo.fr', 2021),
('j-f.chesne@wanadoo.fr', 2022),
('j-f.chesne@wanadoo.fr', 2023),
('jeromedormois@yahoo.fr', 2023),
('jmpatier@yahoo.fr', 2023),
('jmpatier@yahoo.fr', 2024),
('jochen.krauth@sailcoop.fr', 2023),
('jose.levaillant@free.fr', 2023),
('jpc578@gmail.com', 2022),
('jules.pasquier02@gmail.com', 2021),
('jules.pasquier02@gmail.com', 2022),
('julien.bonnefoy@gmail.com', 2021),
('julie_bignon@orange.fr', 2022),
('jurisbob@orange.fr', 2021),
('karina_jeribi@yahoo.fr', 2022),
('karine.audoin@hotmail.com', 2023),
('ken.woehrle@gmail.com', 2021),
('ken.woehrle@gmail.com', 2022),
('l.brochard.archi@gmail.com', 2021),
('l.brochard.archi@gmail.com', 2022),
('laurent.armenaud@laposte.net', 2021),
('lea.baziere@gmail.com', 2021),
('lea.baziere@gmail.com', 2022),
('lebc2228@gmail.com', 2022),
('leore.pujol@oceanascommon.org', 2023),
('lepecheur.g@gmail.com', 2023),
('lepecheur.g@gmail.com', 2024),
('litimat1@free.fr', 2024),
('loic.ff@teamwinds.com', 2021),
('loic.ff@teamwinds.com', 2022),
('lorraine.jacquot@orange.fr', 2022),
('louise.bigot21@gmail.com', 2022),
('ma.bonnefoy@charentelibre.fr', 2021),
('manon.ligonesche@gmail.com', 2024),
('Marc Flye marcflye@aol.com', 2023),
('margotpeutin@gmail.com', 2023),
('mariepierre.labat-camy@csdental.com', 2021),
('mariepierre.labat-camy@csdental.com', 2022),
('marinebulles@outlook.fr', 2021),
('marinebulles@outlook.fr', 2022),
('marmajour@gmail.com', 2021),
('marmajour@gmail.com', 2022),
('marmajour@gmail.com', 2023),
('marrettijacopo@gmail.com', 2022),
('martinmassot@hotmail.com', 2021),
('martinmassot@hotmail.com', 2022),
('maxencearridiaux@gmail.com', 2024),
('mickael.verrier@lilo.org', 2021),
('mickael.verrier@lilo.org', 2022),
('minaud.frederic@gmail.com', 2022),
('mlemeni@yahoo.fr', 2023),
('mlemeni@yahoo.fr', 2024),
('mmdonval@gmail.com', 2021),
('mmdonval@gmail.com', 2022),
('mmdonval@gmail.com', 2023),
('mmdonval@gmail.com', 2024),
('mobydicks.sail@gmail.com', 2021),
('mobydicks.sail@gmail.com', 2022),
('mobydicks.sail@gmail.com', 2023),
('morisseauguillaume@msn.com', 2021),
('morisseauguillaume@msn.com', 2022),
('morisseauguillaume@msn.com', 2024),
('mukojiro123@yahoo.fr', 2021),
('mukojiro123@yahoo.fr', 2022),
('nav.solidaire@gmail.com', 2021),
('nav.solidaire@gmail.com', 2022),
('nav.solidaire@gmail.com', 2023),
('nicogliss46@hotmail.fr', 2021),
('nicogliss46@hotmail.fr', 2022),
('nicolas.movio@gmail.com', 2021),
('nicolas.movio@gmail.com', 2022),
('nicolashuardlamer@gmail.com', 2024),
('nolwennporhiel@gmail.com', 2021),
('nolwennporhiel@gmail.com', 2022),
('olivier@lediouris.net', 2023),
('olivier@lediouris.net', 2024),
('olivieramiot@gmx.fr', 2021),
('olivieramiot@gmx.fr', 2022),
('pa.onfray@orange.fr', 2023),
('paco-andreo@orange.fr', 2021),
('paco-andreo@orange.fr', 2022),
('parramoun@gmail.com', 2024),
('patbenoiton@gmail.com', 2023),
('Patrick.Ballu@cadexi.com', 2021),
('Patrick.Ballu@cadexi.com', 2022),
('patrick.lecoindre@gmail.com', 2023),
('patrick.legait@free.fr', 2023),
('patrick.legait@free.fr', 2024),
('patrick.potiron1@orange.fr', 2021),
('patrick.potiron1@orange.fr', 2022),
('patrick.potiron1@orange.fr', 2023),
('paul.reveillon@gmail.com', 2023),
('paul.rodionoff@gmail.com', 2021),
('paul.rodionoff@gmail.com', 2022),
('paulineantoine1@gmail.com', 2022),
('payen.roland@neuf.fr', 2021),
('payen.roland@neuf.fr', 2022),
('philippe.benoiton@gmail.com', 2023),
('philippe.coindreau@gmail.com', 2021),
('philippe.coindreau@gmail.com', 2022),
('philippe.coindreau@gmail.com', 2023),
('philippe.coindreau@gmail.com', 2024),
('philippe.jacques.roux@orange.fr', 2023),
('pierrebenard@hotmail.com', 2022),
('pmoelo@thalos.fr', 2023),
('prdelfosse@gmail.com', 2023),
('rayondesoleilmh@gmail.com', 2021),
('rayondesoleilmh@gmail.com', 2022),
('rebecca.baudrier.archi@gmail.com', 2021),
('rebecca.baudrier.archi@gmail.com', 2022),
('relation.apadvdl@outlook.fr', 2024),
('remiviolet7@gmail.com', 2024),
('rene.berson@wanadoo.fr', 2023),
('Richard.abadie2@wanadoo.fr', 2023),
('riviere.daniel@club.fr', 2023),
('romainblanc7@gmail.com', 2021),
('romainblanc7@gmail.com', 2022),
('roxanebalan@gmail.com', 2022),
('r_one_71@yahoo.fr', 2023),
('sanchez.claire67@gmail.com', 2021),
('sanchez.claire67@gmail.com', 2022),
('sergebenard7@gmail.com', 2022),
('sigrid.verwaerde@gmail.com', 2021),
('sigrid.verwaerde@gmail.com', 2022),
('solene.tchikladze@yahoo.fr', 2021),
('solene.tchikladze@yahoo.fr', 2022),
('sophie.amable@yacht-concept.fr', 2023),
('sophie.gambier01@gmail.com', 2024),
('stephanehupin@gmail.com', 2021),
('stephanehupin@gmail.com', 2022),
('sylvie.pons-hermieu@laposte.net', 2021),
('sylvie.pons-hermieu@laposte.net', 2022),
('sylviemoniquebarbe@gmail.com', 2023),
('tarriere.benoit@orange.fr', 2021),
('tarriere.benoit@orange.fr', 2022),
('Thibaud.soret@gmail.com', 2022),
('thierry.cherpitel56@gmail.com', 2023),
('tiagocampostc@hotmail.com', 2023),
('unjourdaout@gmail.com', 2021),
('unjourdaout@gmail.com', 2022),
('unjourdaout@gmail.com', 2023),
('unjourdaout@gmail.com', 2024),
('vacher.jean@gmail.com', 2022),
('vallgerard@wanadoo.fr', 2023),
('vernetchris@sfr.fr', 2022),
('vioparcot@gmail.com', 2021),
('vioparcot@gmail.com', 2022),
('xavier.debec@gmail.com', 2021),
('yachtsdupatrimoine@gmail.com', 2021),
('yachtsdupatrimoine@gmail.com', 2022),
('yann.legrand56@icloud.com', 2021),
('yann.legrand56@icloud.com', 2022),
('yl6591@hotmail.fr', 2022),
('yves.milza@gmail.com', 2023),
('yves1@netcourrier.com', 2022);

-- 
--
-- Dumping data for table `THE_FLEET`
--

INSERT INTO `THE_FLEET` (`BOAT_NAME`, `ID`, `PIX_LOC`, `BOAT_TYPE`, `CATEGORY`, `BASE`) VALUES
('Anao', 'anao', '/images/boats/anao.jpeg', 'Folie Douce', 'EX_BOAT', '&Eacute;tel'),
('Ar Mor Van', 'ar-mor-van', '/images/boats/kelt620.jpeg', 'Ketl 620', 'NONE', '&Eacute;tel'),
('Atlantide', 'atlantide', '/images/boats/atlantide.sq.png', 'Gib\'Sea&nbsp;33', 'EX_BOAT', '--'),
('Avel Mad', 'avel-mad', '/images/boats/avel.mad.sq.png', 'Mousquetaire', 'EX_BOAT', 'Le&nbsp;Bono'),
('Babou', 'babou', '/images/boats/babou.sq.png', 'Flying Phantom', 'NONE', 'Saint&#8209;Philibert'),
('Coevic 2', 'coevic-2', '/images/boats/coevic-2.png', 'Mirage 28', 'NONE', 'Lorient'),
('Coraxy', 'coraxy', '/images/boats/coraxy.png', 'Cognac', 'NONE', 'Saint&#8209;Philibert'),
('Don Pedro', 'don-pedro', '/images/boats/dummy.boat.jpg', 'Cheoy Lee 42', 'CLUB', 'San Francisco'),
('Eh\'Tak', 'eh-tak', '/images/boats/eh-tak.jpg', 'Shipman 28', 'CLUB', 'G&acirc;vres'),
('F&eacute;licie', 'felicie', '/images/boats/felicie.sq.png', 'One off Presles', 'EX_BOAT', 'Dakar'),
('Gwenillig', 'gwenillig', '/images/boats/gwenillig.png', 'Eygthene 24', 'NONE', '--'),
('L\'heure bleue', 'heure-bleue', '/images/boats/lheure.bleue.jpeg', 'Arp&egrave;ge', 'NONE', 'Golfe&nbsp;du&nbsp;Morbihan'),
('Ia Orana', 'ia-orana', '/images/boats/ia.orana.sq.png', 'Milord', 'EX_BOAT', '--'),
('Iapyx', 'iapyx', '/images/boats/iapyx.sq.png', 'Offshore&nbsp;35', 'EX_BOAT', '--'),
('Imagine', 'imagine', '/images/boats/selection.png', 'Selection&nbsp;37', 'NONE', 'Ouistreham'),
('Jolly Jumper', 'jolly-jumper', '/images/boats/jolly.jumper.01.jpg', 'First 325', 'NONE', 'Les&nbsp;Sables&nbsp;d\'Olonne'),
('Jules Verne', 'jules-verne', '/images/boats/jules.verne.sq.png', 'Sir 520', 'NONE', 'Locmariaquer'),
('La+R%C3%AAveuse', 'la.reveuse', '/images/boats/la.reveuse.sq.png', 'Damien 40', 'NONE', 'La+Trinit%C3%A9+sur+Mer'),
('Lohengrin', 'lohengrin', '/images/boats/lohengrin/lohengrin.png', 'Ketch en Acier', 'TO_GRAB', 'Arzal'),
('Ma Enez', 'ma-enez', '/images/boats/ma.enez.png', 'Symphonie', 'NONE', 'La&nbsp;Trinit&eacute;'),
('Manu Oviri', 'manu-oviri', '/images/boats/manu-aviri.jpg', 'Comanche 32', 'CLUB', '&Eacute;tel'),
('Melkart', 'melkart', '/images/boats/melkart/melkart.00.jpg', 'Evasion 32', 'NONE', '&Eacute;tel'),
('Melvan', 'melvan', '/images/boats/melvan.sq.png', 'Karat&eacute;&nbsp;33', 'NONE', 'Toulon'),
('Mirella', 'mirella', '/images/boats/mirella.png', 'Maica 12,50', 'NONE', 'Saint&nbsp;Brieuc'),
('Nomadict', 'nomadict', '/images/boats/nomadict/nomadict.00.jpg', 'Gin Fizz', 'TO_GRAB', 'Concarneau'),
('Passpartout', 'passpartout', '/images/boats/passpartout.sq.png', 'One off', 'NONE', 'Lorient'),
('Pordin-Nancq', 'pordin-nancq', '/images/boats/pordin.jpg', 'Carter 37', 'NONE', 'Locmiqu&eacute;lic'),
('Remora', 'remora', '/images/boats/remora.sq.png', 'Arcachonnais', 'TO_GRAB', 'Saint&#8209;Philibert'),
('Rozen an Avel', 'rozen-an-avel', '/images/boats/rozen.an.avel.jpeg', 'Arp&egrave;ge', 'NONE', 'Saint&#8209;Philibert'),
('Saigane', 'saigane', '/images/boats/saigane/saigane.jpg', 'Dufour 2800', 'CLUB', 'Port&nbsp;Blanc'),
('Saudade', 'saudade', '/images/boats/saudade.png', 'Super Arlequin', 'NONE', 'Le&nbsp;Bono'),
('Stiren ar Mor', 'stiren', '/images/boats/stiren.er.mor.png', 'Ghibli', 'NONE', 'La&nbsp;Trinit&eacute;'),
('Taapuna', 'taapuna', '/images/boats/taapuna.png', 'Edel 660', 'CLUB', 'Rivi&egrave;re de Saint&#8209;Philibert'),
('Tokad 2', 'tokad-2', '/images/boats/tokad.2.sq.png', 'Neptune 99', 'CLUB', 'Le&nbsp;Crouesty'),
('Trehudal', 'trehudal', '/images/boats/trehudal.png', 'Nicholson 33', 'CLUB', 'La&nbsp;Trinit&eacute;'),
('Tri Yann', 'tri-yann', '/images/boats/tri.yann.png', 'Trimaran Allegro', 'NONE', 'Saint&#8209;Philibert'),
('Twist Again', 'twist-again', '/images/boats/twist.again.sq.png', 'JOD 35', 'EX_BOAT', 'Saint&#8209;Philibert'),
('Velona', 'velona', '/images/boats/velona/velona.00.jpg', 'Classic Old Gaffer - needs love', 'TO_GRAB', 'Hennebont'),
('Wanita Too', 'wanita', '/images/boats/wanita.too.sq.png', 'First Class 12', 'NONE', 'Saint-Malo');

--
-- Dumping data for table `REFERENTS`
--

INSERT INTO `REFERENTS` (`EMAIL`, `BOAT_ID`, `TELEPHONE`) VALUES
('2l2telecnav@gmail.com', 'coevic-2', '+33 7 56 85 44 38'),
('421jimmypahun@gmail.com', 'pordin-nancq', '+33 6 14 11 20 09'),
('alain.hahusseau@sfr.fr', 'la.reveuse', '+33 7 88 72 41 71'),
('alain.hahusseau@sfr.fr', 'ma-enez', '+33 7 88 72 41 71'),
('alain.hahusseau@sfr.fr', 'rozen-an-avel', '+33 7 88 72 41 71'),
('andres.juan@wanadoo.fr', 'mirella', 'unknown'),
('benjamin.rasseneur@laposte.net', 'ar-mor-van', 'unknown'),
('bmenuet@wanadoo.fr', 'tokad-2', 'unknown'),
('bouan.g@gmail.com', 'melvan', '+33 6 34 33 44 71'),
('contact@passe-coque.com', 'lohengrin', 'unknown'),
('contact@passe-coque.com', 'nomadict', 'unknown'),
('contact@passe-coque.com', 'remora', 'unknown'),
('contact@passe-coque.com', 'velona', 'none'),
('contact@voyageenpatrimoine.fr', 'passpartout', 'unknown'),
('fx.decrecy@voilemagazine.com', 'saudade', 'unknown'),
('garciaalain299@gmail.com', 'jolly-jumper', 'unknown'),
('germain.regis@orange.fr', 'manu-oviri', '+33 6 83 58 47 43'),
('isseo.asso@gmail.com', 'imagine', 'unknown'),
('jeff.allais@hotmail.fr', 'eh-tak', '+33 6 35 59 18 80'),
('l.brochard.archi@gmail.com', 'heure-bleue', 'unknown'),
('lepecheur.g@gmail.com', 'coraxy', 'unknown'),
('litimat1@free.fr', 'trehudal', '+33 6 62 34 88 86'),
('marine.prevet@atelierkopal.fr', 'passpartout', 'unknown'),
('marmajour@gmail.com', 'gwenillig', 'unknown'),
('mlemeni@yahoo.fr', 'stiren', '+33 7 77 60 78 89'),
('morisseauguillaume@msn.com', 'taapuna', 'unknown'),
('olivier.lediouris@gmail.com', 'don-pedro', 'unknown'),
('olivier@lediouris.net', 'don-pedro', 'unknown'),
('patrick.potiron1@orange.fr', 'jolly-jumper', 'unknown'),
('smenuet.evoceane@gmail.com', 'babou', 'unknown'),
('smenuet.evoceane@gmail.com', 'tri-yann', 'unknown'),
('tiagocampostc@hotmail.com', 'melkart', 'unknown'),
('yann.legrand56@icloud.com', 'la.reveuse', '+33 6 75 00 80 15');

INSERT INTO `BOAT_CLUB_MEMBERS` (`EMAIL`, `ENROLLED`, `MEMBER_LEVEL`, `FEE_AMOUNT`, `LAST_FEE_UPDATE`) VALUES
('jeff.allais@hotmail.fr', '2024-04-18 14:21:32', 'SKIPPER', 12.34, NULL),
('olivier.lediouris@gmail.com', '2024-04-16 22:00:00', 'CREW', 23.45, '2024-04-19 22:00:00'),
('olivier@lediouris.net', '2024-04-25 22:00:00', 'SKIPPER', 100, '2024-04-25 22:00:00');

--
-- Dumping data for table `BC_RESERVATIONS`
--

INSERT INTO `BC_RESERVATIONS` (`EMAIL`, `BOAT_ID`, `RESERVATION_DATE`, `FROM_DATE`, `TO_DATE`, `RESERVATION_STATUS`, `MISC_COMMENT`) VALUES
('jeff.allais@hotmail.fr', 'eh-tak', '2024-04-20 08:19:30', '2024-04-21 22:00:00', '2024-04-25 22:00:00', 'REJECTED', 'Jeff goes sailing.'),
('jeff.allais@hotmail.fr', 'eh-tak', '2024-04-20 08:21:50', '2024-05-17 22:00:00', '2024-05-18 22:00:00', 'TENTATIVE', 'Un week end sur l\'eau'),
('Jeff.allais@hotmail.fr', 'eh-tak', '2024-04-24 07:11:54', '2024-05-23 22:00:00', '2024-05-24 22:00:00', 'CONFIRMED', 'From the PHP UI.'),
('jeff.allais@hotmail.fr', 'eh-tak', '2024-04-29 07:02:54', '2024-07-19 22:00:00', '2024-07-26 22:00:00', 'CONFIRMED', 'Semaine en famille poste FÃªtes maritimes de Brest        \r\n               '),
('jeff.allais@hotmail.fr', 'eh-tak', '2024-04-29 07:04:51', '2024-06-27 22:00:00', '2024-06-29 22:00:00', 'TENTATIVE', 'Rubi\'s Cup avec l\'asso'),
('olivier.lediouris@gmail.com', 'eh-tak', '2024-04-18 06:37:02', '2024-04-30 22:00:00', '2024-05-14 22:00:00', 'TENTATIVE', 'This is the first reservation ever.'),
('olivier.lediouris@gmail.com', 'eh-tak', '2024-04-20 10:01:24', '2024-04-19 22:00:00', '2024-04-20 22:00:00', 'REJECTED', 'From the PHP UI.'),
('olivier.lediouris@gmail.com', 'eh-tak', '2024-04-20 10:15:38', '2024-04-19 22:00:00', '2024-04-20 22:00:00', 'REJECTED', 'From the PHP UI.'),
('olivier.lediouris@gmail.com', 'eh-tak', '2024-04-20 10:19:05', '2024-05-19 22:00:00', '2024-05-20 22:00:00', 'TENTATIVE', 'From the PHP UI.'),
('olivier.lediouris@gmail.com', 'eh-tak', '2024-04-20 10:23:00', '2024-06-19 22:00:00', '2024-06-20 22:00:00', 'TENTATIVE', 'From the PHP UI.'),
('olivier.lediouris@gmail.com', 'eh-tak', '2024-04-20 10:59:10', '2024-05-31 22:00:00', '2024-06-01 22:00:00', 'TENTATIVE', 'From the PHP UI.'),
('olivier.lediouris@gmail.com', 'eh-tak', '2024-04-20 11:00:38', '2024-06-02 22:00:00', '2024-06-03 22:00:00', 'TENTATIVE', 'From the PHP UI.'),
('olivier@lediouris.net', 'don-pedro', '2024-04-26 09:40:07', '2024-04-25 22:00:00', '2024-04-29 22:00:00', 'CONFIRMED', 'Projet et Zone de navigation :\r\nPenser aux escapes !!\r\n\r\nÃ‰quipage :\r\n- Joe Shmow, toto@laflotte.bzh\r\n- . . .\r\n\r\nQuestions & commentaires :\r\nOn va partir avec la marÃ©e, on reviendra si on y pense.                \r\n               '),
('olivier@lediouris.net', 'don-pedro', '2024-04-26 10:01:36', '2024-04-09 22:00:00', '2024-04-10 22:00:00', 'TENTATIVE', 'Projet et Zone de navigation :\r\nOn s\'en tamponne !\r\nOn s\'en contre-tape !\r\n\r\nÃ‰quipage :\r\n- Joe Shmow, toto@laflotte.bzh\r\n- . . .\r\n\r\nQuestions & commentaires :\r\nOn va partir avec la marÃ©e, on reviendra si on y pense.                \r\n               ');
